const fs = require("fs");
const path = require("path");
const dotenv = require("dotenv");

function generateEnvExample(
  envFilePath = ".env",
  outputFilePath = ".env.example",
  placeholder = "<YOUR_VALUE_HERE>"
) {
  try {
    // Resolve the full path to the .env file
    const envPath = path.resolve(process.cwd(), envFilePath);

    // Check if .env file exists
    if (!fs.existsSync(envPath)) {
      throw new Error(`No ${envFilePath} file found in the current directory.`);
    }

    // Read and parse the .env file
    const envContent = fs.readFileSync(envPath, "utf8");
    const parsedEnv = dotenv.parse(envContent);

    // Generate the .env.example content
    let exampleContent = "# Generated by genv-ex\n";
    for (const [key, value] of Object.entries(parsedEnv)) {
      exampleContent += `${key}=${placeholder}\n`;
    }

    // Write to the output file
    fs.writeFileSync(
      path.resolve(process.cwd(), outputFilePath),
      exampleContent,
      "utf8"
    );
    console.log(`Successfully created ${outputFilePath} by genv-ex`);
  } catch (error) {
    console.error(`Error: ${error.message}`);
  }
}

module.exports = generateEnvExample;
